set(util_files
  BinPack.cpp
  BinPack.hpp
  Logging.cpp
  MultiStringHash.hpp
  Object.cpp
  Object.hpp
  OStreamCompat.cpp
  StringUnorderedMap.hpp
  StringViewUnorderedSet.hpp
  ToString.cpp
  Util.cpp
  Platform.hpp
  Platform.cpp
  utf8.hpp
  MemoryReader.hpp
  MemoryReader.cpp
  narrow_cast.hpp
)