set(graphics_files
  CBufferPacker.cpp
  CBufferPacker.hpp
  Drawing.cpp
  Font.cpp
  FontImpl.cpp
  FontImpl.hpp
  GraphicsDevice.cpp
  GraphicsDevice.hpp
  GraphicsResource.cpp
  GraphicsResourceImpl.cpp
  GraphicsResourceImpl.hpp
  Image.cpp
  ImageImpl.cpp
  ImageImpl.hpp
  ParticleSystem.cpp
  Shader.cpp
  ShaderImpl.cpp
  ShaderImpl.hpp
  ShaderParameter.hpp
  SpriteBatch.cpp
  SpriteBatch.hpp
  Tessellation2D.cpp
  Tessellation2D.hpp
  TextImpl.hpp
  TextImpl.cpp
  Text.cpp
  VertexElement.hpp
  stb_image.hpp
  stb_image.cpp
  stb_truetype.hpp
  stb_truetype.cpp
  stb_image_write.hpp
  stb_image_write.cpp
)
