set(audio_files
  Audio.cpp
  AudioDevice.cpp
  AudioDevice.hpp
  Sound.cpp
  SoundChannel.cpp
  SoundChannelImpl.cpp
  SoundChannelImpl.hpp
  SoundImpl.cpp
  SoundImpl.hpp
  soloud_audiosource.cpp
  soloud_bus.cpp
  soloud_biquadresonantfilter.cpp
  soloud_duckfilter.cpp
  soloud_echofilter.cpp
  soloud_eqfilter.cpp
  soloud_fader.cpp
  soloud_fft.cpp
  soloud_fftfilter.cpp
  soloud_file.cpp
  soloud_filter.cpp
  soloud_flangerfilter.cpp
  soloud_freeverbfilter.cpp
  soloud_lofifilter.cpp
  soloud_misc.cpp
  soloud_noise.cpp
  soloud_queue.cpp
  soloud_robotizefilter.cpp
  soloud_sfxr.cpp
  soloud_thread.cpp
  soloud_wav.cpp
  soloud_waveshaperfilter.cpp
  soloud_wavstream.cpp
  dr_impl.cpp
  soloud_audiosource.hpp
  soloud_bus.hpp
  soloud.hpp
)
