set(shadercompiler_files
  AST.cpp
  AST.hpp
  ASTOptimizer.cpp
  ASTOptimizer.hpp
  BinOpTable.cpp
  BinOpTable.hpp
  BuiltInSymbols.cpp
  BuiltInSymbols.hpp
  Casting.hpp
  CodeBlock.cpp
  CodeBlock.hpp
  Decl.cpp
  Decl.hpp
  Error.cpp
  Error.hpp
  Expr.cpp
  Expr.hpp
  GLSLShaderGenerator.cpp
  GLSLShaderGenerator.hpp
  Lexer.cpp
  Lexer.hpp
  Naming.cpp
  Naming.hpp
  Parser.cpp
  Parser.hpp
  Scope.cpp
  Scope.hpp
  SemaContext.cpp
  SemaContext.hpp
  ShaderGenerator.cpp
  ShaderGenerator.hpp
  SourceLocation.cpp
  SourceLocation.hpp
  Stmt.cpp
  Stmt.hpp
  TempVarNameGen.cpp
  TempVarNameGen.hpp
  Token.cpp
  Token.hpp
  Type.cpp
  Type.hpp
  TypeCache.cpp
  TypeCache.cpp
  Writer.cpp
  Writer.hpp
)