set(opengl_files
  OpenGLBuffer.cpp
  OpenGLBuffer.hpp
  OpenGLGraphicsDevice.cpp
  OpenGLGraphicsDevice.hpp
  OpenGLImage.cpp
  OpenGLImage.hpp
  OpenGLPrerequisites.cpp
  OpenGLPrerequisites.hpp
  OpenGLPrivateShader.cpp
  OpenGLPrivateShader.hpp
  OpenGLShaderProgram.cpp
  OpenGLShaderProgram.hpp
  OpenGLSpriteBatch.cpp
  OpenGLSpriteBatch.hpp
  OpenGLUserShader.cpp
  OpenGLUserShader.hpp
  OpenGLVao.cpp
  OpenGLVao.hpp
  OpenGLWindow.cpp
  OpenGLWindow.hpp
)