name: CMake Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux-gcc13:
    runs-on: ubuntu-22.04
    container: gcc:13
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt update -y
          apt install -y cmake build-essential libwayland-dev libxkbcommon-dev wayland-protocols \
          extra-cmake-modules xorg-dev libasound2-dev clang-tidy clang-tools

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DCERLIB_ENABLE_TESTS=ON \
          -DCERLIB_BUILD_TESTBED=ON \
          -DCERLIB_BUILD_PLATFORMER_DEMO=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4

  build-windows-vs2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build-win -DCERLIB_ENABLE_TESTS=ON -DCERLIB_BUILD_TESTBED=ON -DCERLIB_BUILD_PLATFORMER_DEMO=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build-win --config ${{env.BUILD_TYPE}} --parallel 4

  build-macos-14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake (Xcode)
        run: |
          cmake -B ${{github.workspace}}/build-macos-14 -G Xcode -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCERLIB_ENABLE_TESTS=ON

      - name: Build (Xcode)
        run: cmake --build ${{github.workspace}}/build-macos-14 --config ${{env.BUILD_TYPE}} --parallel 4

  build-macos-15:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake (Xcode)
        run: |
          cmake -B ${{github.workspace}}/build-macos-15 -G Xcode -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCERLIB_ENABLE_TESTS=ON

      - name: Build (Xcode)
        run: cmake --build ${{github.workspace}}/build-macos-15 --config ${{env.BUILD_TYPE}} --parallel 4
